# Generated by Django 2.1.3 on 2018-11-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
